#!/bin/sh
echo Building UFABC Robotics RCSS
LOG_FILE=build_log.txt

> $LOG_FILE
echo Configuring macros...
echo "################## aclocal ##################" >> $LOG_FILE
echo "" >> $LOG_FILE
aclocal >> $LOG_FILE

echo Configuring configuration commands...
echo "" >> $LOG_FILE
echo "" >> $LOG_FILE
echo "" >> $LOG_FILE
echo "################## autoconf #################" >> $LOG_FILE
echo "" >> $LOG_FILE
autoconf >> $LOG_FILE

echo Configuring making commands...
echo "" >> $LOG_FILE
echo "" >> $LOG_FILE
echo "" >> $LOG_FILE
echo "################## automake #################" >> $LOG_FILE
echo "" >> $LOG_FILE
automake --add-missing >> $LOG_FILE

echo Applying configuration...
echo "" >> $LOG_FILE
echo "" >> $LOG_FILE
echo "" >> $LOG_FILE
echo "################# configure #################" >> $LOG_FILE
echo "" >> $LOG_FILE
./configure >> $LOG_FILE

echo Making...
make |& tee -a $LOG_FILE
